[package]
name = "my-rust-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.41", features = ["std"] }
tracing-subscriber = { version = "0.3.19", features = [
    "env-filter",
    "json",
    "time",
] }
